name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CSharpMcpService/CSharpMcpService.csproj

    - name: Build
      run: dotnet build CSharpMcpService/CSharpMcpService.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test CSharpMcpService/CSharpMcpService.csproj --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish CSharpMcpService/CSharpMcpService.csproj --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish